name: techstars_hackathon
description: "Hackathon Demo App for TechStars"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dotenv: ^4.2.0
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  openai_dart: ^0.4.5
  custom_widgets_toolkit: ^0.0.43
  google_generative_ai: ^0.4.6
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  flutter_markdown: ^0.7.6+2
  page_transition: ^2.2.1
  iconsax_flutter: ^1.0.0
  flutter_chat_ui: ^1.6.15
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/icons/
    - .env


  #-FONTS
  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/AlbertSans/AlbertSans-Regular.ttf
        - asset: assets/fonts/AlbertSans/AlbertSans-Light.ttf
          weight: 100
        - asset: assets/fonts/AlbertSans/AlbertSans-Medium.ttf
          weight: 200
        - asset: assets/fonts/AlbertSans/AlbertSans-MediumItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans/AlbertSans-SemiBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/AlbertSans/AlbertSans-Italic.ttf
          style: italic